language: node_js
node_js:
  - 4.0.0
before_install:
  - rvm install 2.3.1
  - bundle install
  - bundle exec jekyll build

cache:
  bundler: true

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "$FIREBASE_PROJECT"


