sudo: false
language: node_js
node_js:
  - 4.0.0

install:
  - rvm install 2.3.1
  - bundle install

cache:
  bundler: true

script:
  - bundle exec jekyll build
  - ls _site
  - cat _site/index.html

deploy:
  skip_cleanup: true        
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  project: bridgefoundry-website
  on:
    branch: firebase-hosting

