language: node_js
node_js:
  - "node"

install:
  - rvm install 2.3.1
  - gem install bundler
  - bundle install

cache:
  bundler: true

script:
  - git submodule update --init --recursive
  - (cd code-of-conduct-src; bundle; bundle exec jekyll build --destination ../code-of-conduct)
  - (cd workshop-map-src; bundle; bundle exec jekyll build --destination ../workshop-map)
  - bundle exec jekyll build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  project: bridgefoundry-site

