language: node_js
node_js:
  - 4.0.0

install:
  - rvm install 2.3.1
  - bundle install

cache:
  bundler: true

script:
  - bundle exec jekyll build
  - echo "will deploy Firebase project ${FIREBASE_PROJECT}"

deploy:
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  project: "${FIREBASE_PROJECT}"


