language: node_js
node_js:
  - "node"

install:
  - rvm install 2.7
  - gem install bundler
  - bundle install

cache:
  bundler: true

script:
  - git submodule update --init --recursive
  - (cd code-of-conduct-src; bundle; bundle exec jekyll build --destination ../code-of-conduct)
  - (cd workshop-map-src; bundle; bundle exec jekyll build --destination ../workshop-map)
  - bundle exec jekyll build

deploy:
  - provider: firebase
    skip_cleanup: true
    project: bridgefoundry-site
    token:
      secure: "${FIREBASE_TOKEN}"
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    project: bridgefoundry-staging
    token:
      secure: "${FIREBASE_TOKEN}"
    on:
      branch: staging



