language: ruby
rvm:
  - 2.2
cache:
  bundler: true

script:
  - bundle install
  - bundle exec jekyll build
  - firebase deploy --project $FIREBASE_PROJECT -token $FIREBASE_TOKEN

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}

