language: ruby
rvm:
  - 2.2
cache:
  bundler: true
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "$FIREBASE_PROJECT"

before_deploy:
  - bundle install
  - bundle exec jekyll build


